name: first workflow

env:
  WORKFLOW_VAR: "This is a workflow lvl var"
  
on:
 workflow_dispatch:
 
jobs:
 firstjob:
   runs-on: ubuntu-latest
   steps:
     - name: firstJob script
       shell: bash
       run: echo Hello World! This is the first job 
     - uses: actions/checkout@v6
     - name: Print to Log
       id: print-to-log
       uses: actions/hello-world-javascript-action@main
       with:
         who-to-greet: ${{ github.actor }}
     - name: time
       run: |
         echo "The time of the greeting was at: ${{ steps.print-to-log.outputs.time }}"

 secondjob:
   env:
     JOB_VAR: "This is a job variable"
   runs-on: ubuntu-latest
   needs: firstjob
   steps:
     - name: secondJob script
       shell: bash
       run: |
         echo this is the second job
         echo and this is a multi-line script
     - name: environment variables
       env:
         STEP_VAR: "This is a step lvl variable"
       run: |
         echo $WORKFLOW_VAR
         echo $JOB_VAR
         echo $STEP_VAR
         echo "The following is a secret: ${{ secrets.SOME_SECRET }}, of course this wont be displayed in the job logs
         echo "The following are default predefined environment variables"
         echo $GITHUB_ACTOR
         echo $GITHUB_JOB
         echo $GITHUB_REF
         
